# Generated by Django 4.2.5 on 2023-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='modified_at',
            field=models.DateField(blank=True),
        ),
    ]
