# Generated by Django 4.2.5 on 2023-09-29 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_memo_content_alter_memo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='importance',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='study',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
