# Generated by Django 4.2.5 on 2023-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_study_importance_alter_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='repeat',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
